Here we will train and test classification models

In [109]:
import numpy as np
import pandas as pd
import matplotlib as plt
import os
import sys

prepare training and testing data

In [110]:
path = "../../data/dataset.csv"
df = pd.read_csv(path)
df

open     high      low   close   volume         EMA        RSI  \
0     118.84  118.930  118.810  118.85   7965.0  119.030649  25.217323   
1     118.86  118.940  118.850  118.92   6685.0  119.010513  33.712692   
2     118.90  118.960  118.890  118.96  11258.0  119.001322  38.172176   
3     118.96  119.090  118.870  119.06  12015.0  119.011997  47.907058   
4     119.06  119.205  119.020  119.18   8686.0  119.042558  56.945679   
...      ...      ...      ...     ...      ...         ...        ...   
4962  116.00  116.230  115.970  116.12  33440.0  115.873298  70.684044   
4963  116.11  116.160  116.030  116.08  23677.0  115.910880  66.962759   
4964  116.09  116.160  116.080  116.11  29499.0  115.947084  68.351262   
4965  116.10  116.160  116.090  116.13  17173.0  115.980341  69.306807   
4966  116.13  116.170  115.965  115.98  66140.0  115.980279  55.374491   

          MACD  MACD_Signal  %_Change  ...  volume_t-9    RSI_t-9  \
0    -0.105406    -0.067127  0.000252  ...      8263.0  40.746494   
1    -0.108515    -0.075404  0.000589  ...      7813.0  40.151412   
2    -0.106523    -0.081628  0.000336  ...      5205.0  37.774926   
3    -0.095772    -0.084457  0.000841  ...     20692.0  36.608203   
4    -0.076684    -0.082902  0.001008  ...      3531.0  42.359883   
...        ...          ...       ...  ...         ...        ...   
4962  0.036979    -0.009590  0.000948  ...     12611.0  44.439991   
4963  0.052166     0.002762 -0.000344  ...     24784.0  47.651559   
4964  0.065863     0.015382  0.000258  ...     20153.0  46.340338   
4965  0.077439     0.027793  0.000172  ...     17516.0  44.749050   
4966  0.073661     0.036967 -0.001292  ...     27983.0  55.233774   

      %_Change_t-9  Volume_Change_t-9  close_t-10  volume_t-10   RSI_t-10  \
0        -0.000671          -0.176089     119.260      10029.0  45.787648   
1        -0.000084          -0.054460     119.180       8263.0  40.746494   
2        -0.000336          -0.333803     119.170       7813.0  40.151412   
3        -0.000168           2.975408     119.130       5205.0  37.774926   
4         0.000504          -0.829354     119.110      20692.0  36.608203   
...            ...                ...         ...          ...        ...   
4962     -0.000605           0.088657     115.750      11584.0  47.913962   
4963      0.000475           0.965268     115.680      12611.0  44.439991   
4964     -0.000216          -0.186854     115.735      24784.0  47.651559   
4965     -0.000259          -0.130849     115.710      20153.0  46.340338   
4966      0.001642           0.597568     115.680      17516.0  44.749050   

      %_Change_t-10  Volume_Change_t-10  Target  
0         -0.000419            1.401580       1  
1         -0.000671           -0.176089       1  
2         -0.000084           -0.054460       1  
3         -0.000336           -0.333803       1  
4         -0.000168            2.975408       1  
...             ...                 ...     ...  
4962      -0.001036            0.709059       1  
4963      -0.000605            0.088657       0  
4964       0.000475            0.965268       0  
4965      -0.000216           -0.186854       0  
4966      -0.000259           -0.130849       0  

[4967 rows x 65 columns]

In [111]:
features = ['open', 'high','low','close','volume','EMA', 'RSI', 'Target']
data = df
data

open     high      low   close   volume         EMA        RSI  \
0     118.84  118.930  118.810  118.85   7965.0  119.030649  25.217323   
1     118.86  118.940  118.850  118.92   6685.0  119.010513  33.712692   
2     118.90  118.960  118.890  118.96  11258.0  119.001322  38.172176   
3     118.96  119.090  118.870  119.06  12015.0  119.011997  47.907058   
4     119.06  119.205  119.020  119.18   8686.0  119.042558  56.945679   
...      ...      ...      ...     ...      ...         ...        ...   
4962  116.00  116.230  115.970  116.12  33440.0  115.873298  70.684044   
4963  116.11  116.160  116.030  116.08  23677.0  115.910880  66.962759   
4964  116.09  116.160  116.080  116.11  29499.0  115.947084  68.351262   
4965  116.10  116.160  116.090  116.13  17173.0  115.980341  69.306807   
4966  116.13  116.170  115.965  115.98  66140.0  115.980279  55.374491   

          MACD  MACD_Signal  %_Change  ...  volume_t-9    RSI_t-9  \
0    -0.105406    -0.067127  0.000252  ...      8263.0  40.746494   
1    -0.108515    -0.075404  0.000589  ...      7813.0  40.151412   
2    -0.106523    -0.081628  0.000336  ...      5205.0  37.774926   
3    -0.095772    -0.084457  0.000841  ...     20692.0  36.608203   
4    -0.076684    -0.082902  0.001008  ...      3531.0  42.359883   
...        ...          ...       ...  ...         ...        ...   
4962  0.036979    -0.009590  0.000948  ...     12611.0  44.439991   
4963  0.052166     0.002762 -0.000344  ...     24784.0  47.651559   
4964  0.065863     0.015382  0.000258  ...     20153.0  46.340338   
4965  0.077439     0.027793  0.000172  ...     17516.0  44.749050   
4966  0.073661     0.036967 -0.001292  ...     27983.0  55.233774   

      %_Change_t-9  Volume_Change_t-9  close_t-10  volume_t-10   RSI_t-10  \
0        -0.000671          -0.176089     119.260      10029.0  45.787648   
1        -0.000084          -0.054460     119.180       8263.0  40.746494   
2        -0.000336          -0.333803     119.170       7813.0  40.151412   
3        -0.000168           2.975408     119.130       5205.0  37.774926   
4         0.000504          -0.829354     119.110      20692.0  36.608203   
...            ...                ...         ...          ...        ...   
4962     -0.000605           0.088657     115.750      11584.0  47.913962   
4963      0.000475           0.965268     115.680      12611.0  44.439991   
4964     -0.000216          -0.186854     115.735      24784.0  47.651559   
4965     -0.000259          -0.130849     115.710      20153.0  46.340338   
4966      0.001642           0.597568     115.680      17516.0  44.749050   

      %_Change_t-10  Volume_Change_t-10  Target  
0         -0.000419            1.401580       1  
1         -0.000671           -0.176089       1  
2         -0.000084           -0.054460       1  
3         -0.000336           -0.333803       1  
4         -0.000168            2.975408       1  
...             ...                 ...     ...  
4962      -0.001036            0.709059       1  
4963      -0.000605            0.088657       0  
4964       0.000475            0.965268       0  
4965      -0.000216           -0.186854       0  
4966      -0.000259           -0.130849       0  

[4967 rows x 65 columns]

In [112]:
y = data.iloc[:, -1]  
X = data.iloc[:, :-1]  

In [114]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42
)

**Random Forest Classifier:**

In [115]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [116]:
y_pred = rf_model.predict(X_test)

In [117]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.4f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))


Accuracy: 0.5556

Classification Report:
              precision    recall  f1-score   support

           0       0.56      0.59      0.58       635
           1       0.55      0.52      0.53       607

    accuracy                           0.56      1242
   macro avg       0.56      0.55      0.55      1242
weighted avg       0.56      0.56      0.56      1242


Confusion Matrix:
[[374 261]
 [291 316]]


**XGBoost Classifier:**

In [118]:
from xgboost import XGBClassifier

xgb_model = XGBClassifier(random_state=42, n_estimators=100, max_depth=4)
xgb_model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=4, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=None,
              num_parallel_tree=None, random_state=42, ...)

In [119]:
y_pred_xgb = xgb_model.predict(X_test)

In [120]:
accuracy_xgb = accuracy_score(y_test, y_pred_xgb)
print(f"XGBoost Accuracy: {accuracy_xgb:.4f}")
("\nXGBoost Classification Report:")
print(classification_report(y_test, y_pred_xgb))
print("\nXGBoost Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_xgb))

XGBoost Accuracy: 0.5314
              precision    recall  f1-score   support

           0       0.54      0.56      0.55       635
           1       0.52      0.50      0.51       607

    accuracy                           0.53      1242
   macro avg       0.53      0.53      0.53      1242
weighted avg       0.53      0.53      0.53      1242


XGBoost Confusion Matrix:
[[355 280]
 [302 305]]


With superparameters:

In [121]:
from sklearn.model_selection import GridSearchCV

param_grid_xgb = {
    'n_estimators': [100, 200],
    'max_depth': [3, 6, 10],
    'learning_rate': [0.01, 0.1, 0.3],
}

grid_search_xgb = GridSearchCV(estimator=XGBClassifier(random_state=42), param_grid=param_grid_xgb, cv=3)
grid_search_xgb.fit(X_train, y_train)

print("Best parameters for XGBoost:", grid_search_xgb.best_params_)

best_xgb_model = grid_search_xgb.best_estimator_
y_pred_best_xgb = best_xgb_model.predict(X_test)

accuracy_xgb = accuracy_score(y_test, y_pred_best_xgb)
print(f"XGBoost Accuracy: {accuracy_xgb:.4f}")
("\nXGBoost Classification Report:")
print(classification_report(y_test, y_pred_best_xgb))
print("\nXGBoost Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_best_xgb))


Best parameters for XGBoost: {'learning_rate': 0.1, 'max_depth': 3, 'n_estimators': 200}
XGBoost Accuracy: 0.5580
              precision    recall  f1-score   support

           0       0.56      0.59      0.58       635
           1       0.55      0.52      0.54       607

    accuracy                           0.56      1242
   macro avg       0.56      0.56      0.56      1242
weighted avg       0.56      0.56      0.56      1242


XGBoost Confusion Matrix:
[[375 260]
 [289 318]]


****Logistic Regression:****

In [122]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.25, random_state=42
)

In [123]:
from sklearn.linear_model import LogisticRegression

logreg_model = LogisticRegression(max_iter=10000)
logreg_model.fit(X_train, y_train)

LogisticRegression(max_iter=10000)

for regression, we have to firstly scale data

In [124]:
y_pred_logreg = logreg_model.predict(X_test)

In [125]:
accuracy_logreg = accuracy_score(y_test, y_pred)
print(f"Logistic Regression Accuracy: {accuracy_logreg:.4f}")
print("\nLogistic Regression Classification Report:")
print(classification_report(y_test, y_pred))
print("\nLogistic Regression Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))


Logistic Regression Accuracy: 0.5556

Logistic Regression Classification Report:
              precision    recall  f1-score   support

           0       0.56      0.59      0.58       635
           1       0.55      0.52      0.53       607

    accuracy                           0.56      1242
   macro avg       0.56      0.55      0.55      1242
weighted avg       0.56      0.56      0.56      1242


Logistic Regression Confusion Matrix:
[[374 261]
 [291 316]]


**Neural Network:**

In [93]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Dense(64, input_dim=X_train.shape[1], activation='sigmoid'))
model.add(Dense(32, activation='sigmoid'))
model.add(Dense(32, activation='sigmoid'))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

history = model.fit(X_train, y_train, epochs=1000, batch_size=32, validation_data=(X_test, y_test))

Epoch 1/1000


/home/pedro/python_env/lib/python3.12/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


117/117 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.4914 - loss: 0.7610 - val_accuracy: 0.4984 - val_loss: 0.6929
Epoch 2/1000
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.4946 - loss: 0.6932 - val_accuracy: 0.5113 - val_loss: 0.6944
Epoch 3/1000
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5130 - loss: 0.6928 - val_accuracy: 0.5121 - val_loss: 0.6926
Epoch 4/1000
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4978 - loss: 0.6932 - val_accuracy: 0.5121 - val_loss: 0.6936
Epoch 5/1000
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.4950 - loss: 0.6955 - val_accuracy: 0.5024 - val_loss: 0.6927
Epoch 6/1000
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5160 - loss: 0.6934 - val_accuracy: 0.4879 - val_loss: 0.6964
Epoch 7/1000
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5175 - loss: 0.6917 - val_accuracy: 0.4863 - val_loss: 0.6952
Epoch 8/1000
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5117 - loss: 0.6919 - val_accuracy:

In [94]:
y_pred_nn = (model.predict(X_test) > 0.5).astype(int)

39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step 


In [95]:
accuracy_nn = accuracy_score(y_test, y_pred_nn)
print(f"Neural Network Accuracy: {accuracy_nn:.4f}")
print("\nNeural Network Classification Report:")
print(classification_report(y_test, y_pred_nn))
print("\nNeural Network Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_nn))

Neural Network Accuracy: 0.5306

Neural Network Classification Report:
              precision    recall  f1-score   support

           0       0.54      0.54      0.54       635
           1       0.52      0.52      0.52       607

    accuracy                           0.53      1242
   macro avg       0.53      0.53      0.53      1242
weighted avg       0.53      0.53      0.53      1242


Neural Network Confusion Matrix:
[[344 291]
 [292 315]]
