Here we will train and test classification models

In [211]:
import numpy as np
import pandas as pd
import matplotlib as plt
import os
import sys

prepare training and testing data

In [212]:
path = "../../data/dataset.csv"
df = pd.read_csv(path)

In [213]:
features = ['open', 'close', 'high', 'low', 'Target']
data = df
data.head

<bound method NDFrame.head of        Stochastic_K  Target
0         55.932034       1
1         55.932034       1
2         34.000000       1
3         48.484848       1
4         63.636667       1
...             ...     ...
18882     25.173636       0
18883     63.887281       0
18884     59.340182       0
18885     90.154604       0
18886     99.180446       0

[18887 rows x 2 columns]>

In [214]:
y = data.iloc[:, -1]  
X = data.iloc[:, :-1]  

In [215]:
split_index = int(len(X) * 0.75)

X_train, X_test = X[:split_index], X[split_index:]
y_train, y_test = y[:split_index], y[split_index:]

In [216]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)  
X_test = scaler.transform(X_test) 

**Decision Tree:**

In [217]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

rf_model = RandomForestClassifier(n_estimators=100, random_state=42)

rf_model.fit(X_train, y_train)
y_pred_rf = rf_model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred_rf)
print(f"Accuracy: {accuracy:.4f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred_rf))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_rf))

Accuracy: 0.5015

Classification Report:
              precision    recall  f1-score   support

           0       0.40      0.42      0.41      1946
           1       0.58      0.56      0.57      2776

    accuracy                           0.50      4722
   macro avg       0.49      0.49      0.49      4722
weighted avg       0.50      0.50      0.50      4722


Confusion Matrix:
[[ 810 1136]
 [1218 1558]]


**Random Forest Classifier:**

In [218]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

y_pred_rf = rf_model.predict(X_test)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

accuracy = accuracy_score(y_test, y_pred_rf)
print(f"Accuracy: {accuracy:.4f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred_rf))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_rf))


Accuracy: 0.5015

Classification Report:
              precision    recall  f1-score   support

           0       0.40      0.42      0.41      1946
           1       0.58      0.56      0.57      2776

    accuracy                           0.50      4722
   macro avg       0.49      0.49      0.49      4722
weighted avg       0.50      0.50      0.50      4722


Confusion Matrix:
[[ 810 1136]
 [1218 1558]]


**XGBoost Classifier:**

In [219]:
from xgboost import XGBClassifier

xgb_model = XGBClassifier(random_state=42, n_estimators=100, max_depth=4)
xgb_model.fit(X_train, y_train)

y_pred_xgb = xgb_model.predict(X_test)

accuracy_xgb = accuracy_score(y_test, y_pred_xgb)
print(f"XGBoost Accuracy: {accuracy_xgb:.4f}")
("\nXGBoost Classification Report:")
print(classification_report(y_test, y_pred_xgb))
print("\nXGBoost Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_xgb))

XGBoost Accuracy: 0.5500
              precision    recall  f1-score   support

           0       0.40      0.18      0.25      1946
           1       0.58      0.81      0.68      2776

    accuracy                           0.55      4722
   macro avg       0.49      0.50      0.46      4722
weighted avg       0.51      0.55      0.50      4722


XGBoost Confusion Matrix:
[[ 355 1591]
 [ 534 2242]]


****Logistic Regression:****

In [220]:
from sklearn.linear_model import LogisticRegression

logreg_model = LogisticRegression(max_iter=10000)
logreg_model.fit(X_train, y_train)

y_pred_logreg = logreg_model.predict(X_test)

accuracy_logreg = accuracy_score(y_test, y_pred_logreg)
print(f"Logistic Regression Accuracy: {accuracy_logreg:.4f}")
print("\nLogistic Regression Classification Report:")
print(classification_report(y_test, y_pred_logreg))
print("\nLogistic Regression Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_logreg))


Logistic Regression Accuracy: 0.5879

Logistic Regression Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00      1946
           1       0.59      1.00      0.74      2776

    accuracy                           0.59      4722
   macro avg       0.29      0.50      0.37      4722
weighted avg       0.35      0.59      0.44      4722


Logistic Regression Confusion Matrix:
[[   0 1946]
 [   0 2776]]


/home/pedro/python_env/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/pedro/python_env/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/pedro/python_env/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


for regression, we have to firstly scale data

**SVM:**

In [221]:
from sklearn.svm import SVC

svm_model = SVC(kernel='rbf', C=1.0, gamma='scale', random_state=42)
svm_model.fit(X_train, y_train)

y_pred_svm = svm_model.predict(X_test)

accuracy_svm = accuracy_score(y_test, y_pred_svm)
print(f"SVM Accuracy: {accuracy_svm:.4f}")
print("\nSVM Classification Report:")
print(classification_report(y_test, y_pred_svm))
print("\nSVM Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_svm))

SVM Accuracy: 0.5879

SVM Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00      1946
           1       0.59      1.00      0.74      2776

    accuracy                           0.59      4722
   macro avg       0.29      0.50      0.37      4722
weighted avg       0.35      0.59      0.44      4722


SVM Confusion Matrix:
[[   0 1946]
 [   0 2776]]


/home/pedro/python_env/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/pedro/python_env/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/pedro/python_env/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


**LSTM:**

In [188]:
import numpy as np
import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Tworzenie modelu LSTM
lstm_model = Sequential()

# Dodaj warstwę LSTM
lstm_model.add(LSTM(units=50, return_sequences=False, input_shape=(X_train.shape[1], 1)))

# Dodaj warstwę Dropout dla zapobiegania overfittingowi
lstm_model.add(Dropout(0.2))

# Dodaj warstwę Dense (wyjściowa warstwa klasyfikatora)
lstm_model.add(Dense(units=1, activation='sigmoid'))  # Zakładając klasyfikację binarną

# Kompilowanie modelu
lstm_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Trenowanie modelu
lstm_model.fit(X_train, y_train, epochs=100, batch_size=32, validation_data=(X_test, y_test))

# Predykcja na zbiorze testowym
y_pred_lstm = (lstm_model.predict(X_test) > 0.5).astype(int)

# Ocena modelu
accuracy_lstm = accuracy_score(y_test, y_pred_lstm)
print(f"LSTM Accuracy: {accuracy_lstm:.4f}")
print("\nLSTM Classification Report:")
print(classification_report(y_test, y_pred_lstm))
print("\nLSTM Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_lstm))

Epoch 1/100


/home/pedro/python_env/lib/python3.12/site-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5102 - loss: 0.6926 - val_accuracy: 0.5652 - val_loss: 0.6859
Epoch 2/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5213 - loss: 0.6906 - val_accuracy: 0.5584 - val_loss: 0.6847
Epoch 3/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5180 - loss: 0.6916 - val_accuracy: 0.5531 - val_loss: 0.6841
Epoch 4/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5220 - loss: 0.6909 - val_accuracy: 0.5652 - val_loss: 0.6836
Epoch 5/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5391 - loss: 0.6902 - val_accuracy: 0.5659 - val_loss: 0.6836
Epoch 6/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5265 - loss: 0.6917 - val_accuracy: 0.5546 - val_loss: 0.6839
Epoch 7/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5367 - loss: 0.6890 - val_accuracy: 0.5629 - val_loss: 0.6841
Epoch 8/100
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5279 - loss: 0.6928 - val_accuracy: 0.5659

**Neural Network:**

In [61]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Dense(64, input_dim=X_train.shape[1], activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

history = model.fit(X_train, y_train, epochs=100, batch_size=32, validation_data=(X_test, y_test))

Epoch 1/100


/home/pedro/python_env/lib/python3.12/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


117/117 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5064 - loss: 0.6939 - val_accuracy: 0.5248 - val_loss: 0.6928
Epoch 2/100
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5128 - loss: 0.6934 - val_accuracy: 0.5216 - val_loss: 0.6928
Epoch 3/100
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.4837 - loss: 0.6949 - val_accuracy: 0.5216 - val_loss: 0.6928
Epoch 4/100
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5038 - loss: 0.6925 - val_accuracy: 0.5112 - val_loss: 0.6928
Epoch 5/100
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5135 - loss: 0.6932 - val_accuracy: 0.5216 - val_loss: 0.6928
Epoch 6/100
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5058 - loss: 0.6934 - val_accuracy: 0.5216 - val_loss: 0.6930
Epoch 7/100
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5190 - loss: 0.6928 - val_accuracy: 0.5256 - val_loss: 0.6931
Epoch 8/100
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4995 - loss: 0.6933 - val_accuracy: 0.5040

In [62]:
y_pred_nn = (model.predict(X_test) > 0.5).astype(int)

accuracy_nn = accuracy_score(y_test, y_pred_nn)
print(f"Neural Network Accuracy: {accuracy_nn:.4f}")
print("\nNeural Network Classification Report:")
print(classification_report(y_test, y_pred_nn))
print("\nNeural Network Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_nn))

39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 871us/step
Neural Network Accuracy: 0.5112

Neural Network Classification Report:
              precision    recall  f1-score   support

           0       0.52      0.88      0.65       651
           1       0.46      0.11      0.18       597

    accuracy                           0.51      1248
   macro avg       0.49      0.49      0.42      1248
weighted avg       0.49      0.51      0.43      1248


Neural Network Confusion Matrix:
[[571  80]
 [530  67]]


In [ ]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.25, random_state=42
)